version: "3.9"

services:
  db:
    image: postgres:12.1
    volumes:
      - pg_data:/var/lib/postgresql/data
    container_name: django_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    env_file:
      - environment.env

  django:
    build:
      context: .
    command: python mysite/manage.py runserver 0.0.0.0:4545
    container_name: django
    volumes:
      - .:/code
    ports:
      - "4545:4545"
    depends_on:
      - db

  fastapi:
    build:
      dockerfile: fastapi.Dockerfile
    command: uvicorn app:app --reload --proxy-headers --host 0.0.0.0 --port 8000
    container_name: fastapi
    volumes:
      - ./fastapi:/code
    ports:
      - "8000:8000"

volumes:
  pg_data:
    driver: local